# Generated by Django 5.0 on 2025-09-30 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.clientprofile'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.freelancerprofile'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_skills',
            field=models.ManyToManyField(to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.ManyToManyField(to='jobs.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('job', 'freelancer')},
        ),
    ]
