# Generated by Django 5.0 on 2025-09-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='categories_of_expertise',
            field=models.CharField(blank=True, choices=[('web_development', 'Web Development'), ('graphic_design', 'Graphic Design'), ('content_writing', 'Content Writing'), ('digital_marketing', 'Digital Marketing'), ('data_analysis', 'Data Analysis'), ('customer_service', 'Customer Service'), ('other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='job_type_preferences',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary')], max_length=100),
        ),
    ]
