# Generated by Django 5.0 on 2025-10-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_freelancerprofile_categories_of_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='github_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='linked_in_profile',
            field=models.URLField(blank=True),
        ),
    ]
