# Generated by Django 5.0 on 2025-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_proposalai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalai',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
