# Generated by Django 5.0 on 2025-10-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_freelancerprofile_github_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='cv',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
