# Generated by Django 5.0 on 2025-11-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalai',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
