# Generated by Django 5.0 on 2025-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_freelancerprofile_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jobs.skill'),
        ),
    ]
