# Generated by Django 5.0 on 2025-11-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_proposalai_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='interview_availability',
            field=models.BooleanField(default=False),
        ),
    ]
