# Generated by Django 5.0 on 2025-11-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobpost_interview_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
